//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Birim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Birim()
        {
            this.Faturas = new HashSet<Fatura>();
            this.FaturaSatirlaris = new HashSet<FaturaSatirlari>();
            this.Malzemelers = new HashSet<Malzemeler>();
        }
        [Display(Name ="Birim ÝD")]
        public int Birim_ID { get; set; }
        [Display(Name ="Birim Kodu")]
        public string BirimKodu { get; set; }
        [Display(Name = "Kullanýcý ÝD")]
        public Nullable<int> Kullanici_ID { get; set; }
        [Display(Name = "Birim Adý")]
        public string BirimAdi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Faturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaSatirlari> FaturaSatirlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Malzemeler> Malzemelers { get; set; }
    }
}
