//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cari()
        {
            this.Faturas = new HashSet<Fatura>();
        }
        [Display(Name = "Cari ÝD")]
        public int Cari_ID { get; set; }
        [Display(Name = "Cari Kodu")]
        public string CariKodu { get; set; }
        [Display(Name = "Taným")]
        public string Tanim { get; set; }
        [Display(Name = "Adres")]
        public string Adres { get; set; }
        [Display(Name = "Ülke")]
        public string Ulke { get; set; }
        [Display(Name = "Þehir")]
        public string Sehir { get; set; }
        [Display(Name = "Ýlçe")]
        public string Ilce { get; set; }

        [Display(Name = "Telefon Numarasý")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> Tel { get; set; }
        [Display(Name = "Fax Numarasý")]
        public Nullable<int> Fax { get; set; }
        [Display(Name = "E-posta")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Web Adresi")]
        public string Web { get; set; }
        [Display(Name = "Posta Kodu")]
        [DataType(DataType.PostalCode)]

        public Nullable<int> PostaKodu { get; set; }
        [Display(Name = "Aktif")]
        public Nullable<bool> Aktif { get; set; }
        [Display(Name = "Fatura Satýrlarý ÝD")]
        public Nullable<int> FaturaSatirlari_ID { get; set; }
        [Display(Name = "Kullanýcý ÝD")]
        public Nullable<int> Kullanici_ID { get; set; }
    
        public virtual FaturaSatirlari FaturaSatirlari { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Faturas { get; set; }
    }
}
