//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cari()
        {
            this.Faturas = new HashSet<Fatura>();
        }
        [Display(Name ="Cari Ýd")]
        public int Cari_ID { get; set; }
        [Display(Name = "Cari Kodu")]

        public string CariKodu { get; set; }
        [Display(Name = "Taným")]

        public string Tanim { get; set; }
       

        public string Adres { get; set; }
        [Display(Name = "Ülke")]


        public string Ulke { get; set; }
        [Display(Name = "Þehir")]

        public string Sehir { get; set; }
        [Display(Name = "Ýlçe")]

        public string Ilce { get; set; }
        [Display(Name = "Telefon Numarasý")]

        [Required(ErrorMessage ="Lütfen bu alaný boþ geçmeyiniz.")]
       [DataType(DataType.PhoneNumber,ErrorMessage ="Lütfen geçerli formatta bilgi giriniz.")]
        public Nullable<int> Tel { get; set; }
        [Display(Name = "Fax numarasý")]

        public Nullable<int> Fax { get; set; }
        [Display(Name = "E-mail")]

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Web Adresi")]

        public string Web { get; set; }
        [Display(Name = "Posta Kodu")]

        [DataType(DataType.PostalCode)]
        public Nullable<int> PostaKodu { get; set; }
        

        public Nullable<bool> Aktif { get; set; }
        [Display(Name = "Datura Satýrlarý Ýd")]

        public Nullable<int> FaturaSatirlari_ID { get; set; }
        [Display(Name = "Kullanýcý Ýd")]

        public Nullable<int> Kullanici_ID { get; set; }
    
        public virtual FaturaSatirlari FaturaSatirlari { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Faturas { get; set; }
        public List<Cari> ListOfCari { get; set; }
    }
}
