//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cariler
    {
        public int C_ID { get; set; }
        public Nullable<int> Aktif { get; set; }
        public string CariKodu { get; set; }
        public Nullable<int> FS_ID { get; set; }
        public string Tanim { get; set; }
        public Nullable<int> F_ID { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string Adres { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public Nullable<int> Tel { get; set; }
        public Nullable<int> Fax { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public Nullable<int> PostaKodu { get; set; }
    
        public virtual Fatura Fatura { get; set; }
        public virtual FaturaSatirlari FaturaSatirlari { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
