//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaSatirlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FaturaSatirlari()
        {
            this.Caris = new HashSet<Cari>();
        }
    
        public int Faturasatirlari_ID { get; set; }
        public Nullable<int> TRCode { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> FaturaReferansi { get; set; }
        public Nullable<int> FaturaSatirNumarasi { get; set; }
        public Nullable<double> Toplam { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<int> BirimReferansi { get; set; }
        public Nullable<int> BİrimSetReferansi { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> NetKDV { get; set; }
        public Nullable<double> KDVEsasTutari { get; set; }
        public string Iptal { get; set; }
        public Nullable<int> Birim_ID { get; set; }
        public Nullable<int> Fatura_ID { get; set; }
        public Nullable<int> Malzeme_ID { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
    
        public virtual Birim Birim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cari> Caris { get; set; }
        public virtual Fatura Fatura { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Malzemeler Malzemeler { get; set; }
    }
}
