//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Birims = new HashSet<Birim>();
            this.Caris = new HashSet<Cari>();
            this.Faturas = new HashSet<Fatura>();
            this.FaturaSatirlaris = new HashSet<FaturaSatirlari>();
            this.Malzemelers = new HashSet<Malzemeler>();
        }
        [Display(Name = "Kullanýcý ÝD")]
        public int Kullanici_ID { get; set; }
        [Display(Name = "Kullanýcý Adý")]
        
        public string KullaniciAdi { get; set; }
        [Display(Name = "Ýsim")]
        public string Isim { get; set; }
        [Display(Name = "Þifre")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
        [Display(Name = "Soy Ýsim")]
        public string SoyIsim { get; set; }
     
        public Nullable<int> YetkiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birim> Birims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cari> Caris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Faturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaSatirlari> FaturaSatirlaris { get; set; }
        public virtual Yetkilendirme Yetkilendirme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Malzemeler> Malzemelers { get; set; }
    }
}
