//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Malzemeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Malzemeler()
        {
            this.FaturaSatirlaris = new HashSet<FaturaSatirlari>();
        }
        [Display(Name = "Malzeme Ýd")]

        public int Malzeme_ID { get; set; }
        [Display(Name = "Malzeme Ýd")]

        public string MalzemeKodu { get; set; }
        [Display(Name = "Malzeme Kodu")]

        public string MalzemeAdi { get; set; }
        [Display(Name = "Özel Kod")]

        public string OzelKod { get; set; }
        public Nullable<double> KDV { get; set; }
        [Display(Name = "Oluþturma Tarihi")]

        public Nullable<System.DateTime> OlusturmaTarihi { get; set; } = DateTime.Now;


        [Display(Name = "Düzenlenme Tarihi")]

        public Nullable<System.DateTime> DuzenlemeTarihi { get; set; } = DateTime.UtcNow;
        [Display(Name = "Kullanýcý Ýd")]

        public Nullable<int> Kullanici_ID { get; set; }
        [Display(Name = "Birim Ýd")]

        public Nullable<int> Birim_ID { get; set; }
    
        public virtual Birim Birim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaSatirlari> FaturaSatirlaris { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
